server:
  port: 8080
spring:
  application:
    name: storageServer
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: helloWRLD
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
