server:
  port: 8083
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://user_db:5432/postgres3
    username: postgres
    password: helloWRLD
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  fetch-registry: true
  register-with-eureka: true