server:
  port: 8080
spring:
  application:
    name: storage-service
  datasource:
    url: jdbc:postgresql://storage_db:5432/postgres
    username: postgres
    password: helloWRLD
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  fetch-registry: true
  register-with-eureka: true